name: Trigger Target Repository Workflow

on:
  push:
    branches:
      - main  # You can change this to the branch you want to monitor

jobs:
  trigger-target-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Target Repository Workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -d '{"ref":"main"}' \
            https://api.github.com/repos/SRINATHR2001/target/actions/workflows/blank.yml/dispatches
